Fix a joinedload in ability list query
We were asking for `joinedload('prose.short_effect')`, which doesn't
make any sense -- short_effect is a column, not a relation -- and
SQLAlchemy 1.3 rightly complains:

    LoaderStrategyException: Can't apply "joined loader" strategy to
        property "ability_prose.short_effect", which is a "column property";
        this loader strategy is intended to be used with a "relationship
        property".

Besides, we actually want to load `local_prose.short_effect`, not
`prose.short_effect`.

Fixes #129